Traceback (most recent call last):
  File "/home/nelo/miniconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/nelo/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nelo/miniconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nelo/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nelo/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/nelo/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/nelo/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from regression import calculate_error, get_train_test_validation
from sklearn.linear_model import LinearRegression 
from sklearn.ensemble import BaggingRegressor


X_train, X_test, X_val, y_train, y_test, y_val = get_train_test_validation()

base_regressor = LinearRegression()

bagging_regressor = BaggingRegressor(base_regressor, n_estimators=100, random_state=42)
bagging_regressor.fit(X_train, y_train)
y_pred = bagging_regressor.predict(X_val)

calculate_error(y_val, y_pred)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 6[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlinear_model[39;00m [38;5;28;01mimport[39;00m LinearRegression 
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mensemble[39;00m [38;5;28;01mimport[39;00m BaggingRegressor
[0;32m----> 6[0m X_train, X_test, X_val, y_train, y_test, y_val [38;5;241m=[39m [43mget_train_test_validation[49m[43m([49m[43m)[49m
[1;32m      8[0m base_regressor [38;5;241m=[39m LinearRegression()
[1;32m     10[0m bagging_regressor [38;5;241m=[39m BaggingRegressor(base_regressor, n_estimators[38;5;241m=[39m[38;5;241m100[39m, random_state[38;5;241m=[39m[38;5;241m42[39m)

File [0;32m/mnt/Datos/proyectos/Especialidad BigDataIA/repositorios/sistemas_aprendizaje_automatico/apuntes_web/markdowns/sistemas_supervisados/regresion/modelos/../../../../code/regression.py:35[0m, in [0;36mget_train_test_validation[0;34m(path)[0m
[1;32m     33[0m [38;5;28;01mdef[39;00m [38;5;21mget_train_test_validation[39m(path[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m---> 35[0m     X, y [38;5;241m=[39m [43mget_X_y[49m[43m([49m[43mpath[49m[43m)[49m
[1;32m     37[0m     X_train, X_test, y_train, y_test [38;5;241m=[39m train_test_split(X, y, test_size[38;5;241m=[39m[38;5;241m0.2[39m, random_state[38;5;241m=[39m[38;5;241m1[39m)
[1;32m     38[0m     X_train, X_val, y_train, y_val [38;5;241m=[39m train_test_split(X_train, y_train, test_size[38;5;241m=[39m[38;5;241m0.25[39m, random_state[38;5;241m=[39m[38;5;241m1[39m)

File [0;32m/mnt/Datos/proyectos/Especialidad BigDataIA/repositorios/sistemas_aprendizaje_automatico/apuntes_web/markdowns/sistemas_supervisados/regresion/modelos/../../../../code/regression.py:15[0m, in [0;36mget_X_y[0;34m(path)[0m
[1;32m     13[0m [38;5;28;01mif[39;00m path:
[1;32m     14[0m     PATH_TO_CSV [38;5;241m=[39m path
[0;32m---> 15[0m df [38;5;241m=[39m pd[38;5;241m.[39mread_csv([43mPATH_TO_CSV[49m [38;5;241m+[39m [38;5;124m'[39m[38;5;124minsurance_preprocesed.csv[39m[38;5;124m'[39m)
[1;32m     16[0m df [38;5;241m=[39m df[38;5;241m.[39mdrop([[38;5;124m'[39m[38;5;124mNo[39m[38;5;124m'[39m], axis[38;5;241m=[39m[38;5;241m1[39m)
[1;32m     17[0m X [38;5;241m=[39m df[38;5;241m.[39mcopy()[38;5;241m.[39mdrop([[38;5;124m'[39m[38;5;124mcharges[39m[38;5;124m'[39m], axis[38;5;241m=[39m[38;5;241m1[39m)

[0;31mUnboundLocalError[0m: cannot access local variable 'PATH_TO_CSV' where it is not associated with a value

